# Generated by Django 5.0.1 on 2025-06-03 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_customuser_foto_perfil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='foto_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
