# Generated by Django 5.0.1 on 2025-06-05 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_foto_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
