# Generated by Django 5.0.1 on 2025-06-05 17:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils.timezone import now

class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={
                'ordering': ['-created_at'],
                'verbose_name': 'Historia Familiar',
                'verbose_name_plural': 'Historias Familiares'
            },
        ),
        migrations.RemoveField(
            model_name='story',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='story',
            name='contenido',
        ),
        migrations.RemoveField(
            model_name='story',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='story',
            name='titulo',
        ),
        migrations.AddField(
            model_name='story',
            name='author',
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name='Autor'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='content',
            field=models.TextField(
                default='',
                blank=True,
                verbose_name='Contenido de la Historia'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='created_at',
            field=models.DateTimeField(default=now,verbose_name='Fecha de Creación'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='title',
            field=models.CharField(
                default='desconocido',
                max_length=200,
                verbose_name='Título'
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='story',
            name='updated_at',
            field=models.DateTimeField(
                default=now,
                verbose_name='Última Actualización'
            ),
            preserve_default=False,
        ),
    ]
    
