# Generated by Django 5.0.1 on 2025-06-05 23:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-uploaded_at'], 'verbose_name': 'Foto Familiar', 'verbose_name_plural': 'Fotos Familiares'},
        ),
        migrations.RemoveField(
            model_name='photo',
            name='autor',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='fecha_subida',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='titulo',
        ),
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Descripción/Comentario'),
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='photos/', verbose_name='Imagen'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Título (Opcional)'),
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Subida'),
        ),
        migrations.AddField(
            model_name='photo',
            name='uploaded_by',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Subido por'),
            preserve_default=False,
        ),
    ]
