# Generated by Django 5.0.1 on 2025-06-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_foto_member_foto_perfil'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name_paterno', 'first_name'], 'verbose_name': 'Miembro de la Familia', 'verbose_name_plural': 'Miembros de la Familia'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='member',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='member',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='member',
            name='relacion',
        ),
        migrations.RemoveField(
            model_name='member',
            name='resumen',
        ),
        migrations.RemoveField(
            model_name='member',
            name='telefono',
        ),
        migrations.AddField(
            model_name='member',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección'),
        ),
        migrations.AddField(
            model_name='member',
            name='address_conyuge',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Dirección Cónyuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='apodo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apodo'),
        ),
        migrations.AddField(
            model_name='member',
            name='apodo_conyuge',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Apodo Cónyuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='member',
            name='birth_date_conyuge',
            field=models.DateField(blank=True, null=True, verbose_name=' de Nacimiento Cónyuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='correomail',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='member',
            name='correomail_conyuge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico Cónyuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='dead_date_conyuge',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fallec.Cónyuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='dead_date_madre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fallec.Madre'),
        ),
        migrations.AddField(
            model_name='member',
            name='dead_date_padre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fallec.Padre'),
        ),
        migrations.AddField(
            model_name='member',
            name='estudios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estudios-Títulos'),
        ),
        migrations.AddField(
            model_name='member',
            name='estudios_conyuge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estudios-Títulos Conyuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='facebook',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook'),
        ),
        migrations.AddField(
            model_name='member',
            name='facebook_conyuge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Facebook Cónyuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='fallecimiento_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Fallecimiento'),
        ),
        migrations.AddField(
            model_name='member',
            name='fechanacmadre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento Madre'),
        ),
        migrations.AddField(
            model_name='member',
            name='fechanacpadre',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento Padre'),
        ),
        migrations.AddField(
            model_name='member',
            name='first_name',
            field=models.CharField(default='NombreDesconocido', max_length=100, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='member',
            name='first_name_conyuge',
            field=models.CharField(blank=True, default='NombreDesconocido', max_length=100, null=True, verbose_name='Nombre Cónyuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='foto_conyuge',
            field=models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='Foto Cónyuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='foto_madre',
            field=models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='Foto Madre'),
        ),
        migrations.AddField(
            model_name='member',
            name='foto_padre',
            field=models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='Foto Padre'),
        ),
        migrations.AddField(
            model_name='member',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='Foto Principal'),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name_conyuge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Cónyuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name_materno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='member',
            name='last_name_paterno',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Paterno'),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Linkedin'),
        ),
        migrations.AddField(
            model_name='member',
            name='linkedin_conyuge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Linkedin Cónyuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='lugar_de_residencia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar Residencia'),
        ),
        migrations.AddField(
            model_name='member',
            name='lugar_de_residencia_conyuge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar Residencia Cónyuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AddField(
            model_name='member',
            name='lugar_nacimiento_conyuge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar de Nacimiento Cónyuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='madre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Madre'),
        ),
        migrations.AddField(
            model_name='member',
            name='madrina_de_bautismo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Madrina Bautismo'),
        ),
        migrations.AddField(
            model_name='member',
            name='ocupación',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación/Profesión'),
        ),
        migrations.AddField(
            model_name='member',
            name='ocupación_conyuge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación/Profesión Cónyuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='padre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Padre'),
        ),
        migrations.AddField(
            model_name='member',
            name='padrino_de_bautismo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Padrino Bautismo'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Teléfono'),
        ),
        migrations.AddField(
            model_name='member',
            name='phone_number_conyuge',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número de Teléfono Cónyuge'),
        ),
        migrations.AddField(
            model_name='member',
            name='relationship',
            field=models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('HIJO', 'Hijo/a'), ('HERMANO', 'Hermano/a'), ('ABUELO', 'Abuelo/a'), ('TIO', 'Tío/a'), ('PRIMO', 'Primo/a'), ('OTRO', 'Otro')], default='OTRO', max_length=20, verbose_name='Relación'),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WhatsApp'),
        ),
        migrations.AddField(
            model_name='member',
            name='whatsapp_conyuge',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='WhatsApp Cónyuge'),
        ),
    ]
