# Generated by Django 5.0.1 on 2025-06-05 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_options_remove_member_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='address_conyuge',
            field=models.TextField(blank=True, null=True, verbose_name='Dirección Cónyuge'),
        ),
    ]
