# Generated by Django 4.2 on 2025-06-07 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_member_address_conyuge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='address_conyuge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='apodo_conyuge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='birth_date_conyuge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='correomail_conyuge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='dead_date_conyuge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='dead_date_madre',
        ),
        migrations.RemoveField(
            model_name='member',
            name='dead_date_padre',
        ),
        migrations.RemoveField(
            model_name='member',
            name='estudios_conyuge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='facebook_conyuge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='fechanacmadre',
        ),
        migrations.RemoveField(
            model_name='member',
            name='fechanacpadre',
        ),
        migrations.RemoveField(
            model_name='member',
            name='first_name_conyuge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='foto_conyuge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='foto_madre',
        ),
        migrations.RemoveField(
            model_name='member',
            name='foto_padre',
        ),
        migrations.RemoveField(
            model_name='member',
            name='last_name_conyuge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='linkedin_conyuge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lugar_de_residencia',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lugar_de_residencia_conyuge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='lugar_nacimiento_conyuge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='ocupación_conyuge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_number_conyuge',
        ),
        migrations.RemoveField(
            model_name='member',
            name='whatsapp_conyuge',
        ),
        migrations.AddField(
            model_name='member',
            name='conyuge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conyuges', to='members.member', verbose_name='Cónyuge'),
        ),
        migrations.AlterField(
            model_name='member',
            name='correomail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='member',
            name='estudios',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estudios/Títulos'),
        ),
        migrations.AlterField(
            model_name='member',
            name='facebook',
            field=models.URLField(blank=True, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='member',
            name='linkedin',
            field=models.URLField(blank=True, null=True, verbose_name='LinkedIn'),
        ),
        migrations.AlterField(
            model_name='member',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_de_la_madre', to='members.member', verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_del_padre', to='members.member', verbose_name='Padre'),
        ),
    ]
