# Generated by Django 4.2 on 2025-06-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_remove_member_address_conyuge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombres'),
        ),
    ]
