# Generated by Django 5.0.1 on 2025-06-10 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_alter_member_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='relationship',
            field=models.CharField(choices=[('TATARABUELO', '1ra Generación'), ('BISABUELO', '2da Generación'), ('ABUELO', '3ra Generación'), ('PADRE_MADRE', '4ta Generación'), ('HIJO_HIJA', '5ta Generación'), ('NIETO_NIETA', '6ta Generación'), ('HERMANO', 'Hermano/a'), ('TIO', 'Tío/a'), ('PRIMO', 'Primo/a'), ('CONYUGE', 'Cónyuge')], default='CONYUGE', max_length=20, verbose_name='Relación'),
        ),
    ]
