# Generated by Django 4.2 on 2025-06-20 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_alter_member_relationship'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name_paterno', 'first_name'], 'verbose_name': 'Miembro', 'verbose_name_plural': 'Miembros'},
        ),
        migrations.AlterField(
            model_name='member',
            name='apodo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Apodo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='conyuge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conyuge_de', to='members.member', verbose_name='Cónyuge'),
        ),
        migrations.AlterField(
            model_name='member',
            name='correomail',
            field=models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='member',
            name='estudios',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Estudios'),
        ),
        migrations.AlterField(
            model_name='member',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='Foto Principal'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='member',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_por_madre', to='members.member', verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='madrina_de_bautismo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Madrina de Bautismo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='ocupación',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='member',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_por_padre', to='members.member', verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='padrino_de_bautismo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Padrino de Bautismo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='relationship',
            field=models.CharField(blank=True, choices=[('TATARABUELO', '1ra Generación'), ('BISABUELO', '2da Generación'), ('ABUELO', '3ra Generación'), ('PADRE_MADRE', '4ta Generación'), ('HIJO_HIJA', '5ta Generación'), ('NIETO_NIETA', '6ta Generación'), ('HERMANO', 'Hermano/a'), ('TIO', 'Tío/a'), ('PRIMO', 'Primo/a'), ('CONYUGE', 'Cónyuge')], max_length=50, null=True, verbose_name='Relación'),
        ),
    ]
