# Generated by Django 4.2 on 2025-06-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_alter_member_options_alter_member_apodo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='relationship',
            field=models.CharField(blank=True, choices=[('TATARABUELO', '1ra Generación'), ('BISABUELO', '2da Generación'), ('ABUELO', '3ra Generación'), ('PADRE_MADRE', '4ta Generación'), ('HIJO_HIJA', '5ta Generación'), ('NIETO_NIETA', '6ta Generación'), ('BISNIETO', '7ma Generación'), ('TATARANIETO', '8va Generación'), ('CHOZNO', '9na Generación'), ('HERMANO', 'Hermano/a'), ('TIO', 'Tío/a'), ('PRIMO', 'Primo/a'), ('CONYUGE', 'Cónyuge')], max_length=50, null=True, verbose_name='Relación'),
        ),
    ]
