# Generated by Django 4.2 on 2025-06-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_member_relationship'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'Masculino'), ('FEMENINO', 'Femenino'), ('OTRO', 'Otro'), ('PREFIERO_NO_DECIR', 'Prefiero no decir')], max_length=20, null=True, verbose_name='Género'),
        ),
    ]
