# Generated by Django 4.2 on 2025-06-27 00:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0010_member_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='gender',
        ),
    ]
