# Generated by Django 5.0.1 on 2025-06-29 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_remove_member_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Instagram'),
        ),
    ]
