# Generated by Django 4.2 on 2026-03-03 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_member_instagram'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='ocupación',
            new_name='ocupacion',
        ),
    ]
