# Generated by Django 4.2 on 2026-03-25 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_rename_ocupación_member_ocupacion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': 'Miembro', 'verbose_name_plural': 'Miembros'},
        ),
        migrations.AddField(
            model_name='member',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/', verbose_name='Código QR de Acceso'),
        ),
        migrations.AlterField(
            model_name='member',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='member',
            name='conyuge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conyuge_de', to='members.member', verbose_name='Cónyuge'),
        ),
        migrations.AlterField(
            model_name='member',
            name='correomail',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='member',
            name='estudios',
            field=models.TextField(blank=True, null=True, verbose_name='Estudios'),
        ),
        migrations.AlterField(
            model_name='member',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='members/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='member',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_madre', to='members.member', verbose_name='Madre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='madrina_de_bautismo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Madrina de Bautismo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='ocupacion',
            field=models.TextField(blank=True, null=True, verbose_name='Ocupación/Oficio'),
        ),
        migrations.AlterField(
            model_name='member',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_padre', to='members.member', verbose_name='Padre'),
        ),
        migrations.AlterField(
            model_name='member',
            name='padrino_de_bautismo',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Padrino de Bautismo'),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='member',
            name='relationship',
            field=models.CharField(blank=True, choices=[('TATARABUELO', '1ra Generación'), ('BISABUELO', '2da Generación'), ('ABUELO', '3ra Generación'), ('PADRE_MADRE', '4ta Generación'), ('HIJO_HIJA', '5ta Generación'), ('NIETO_NIETA', '6ta Generación'), ('BISNIETO', '7ma Generación'), ('TATARANIETO', '8va Generación'), ('CHOZNO', '9na Generación'), ('HERMANO', 'Hermano/a'), ('TIO', 'Tío/a'), ('PRIMO', 'Primo/a'), ('CONYUGE', 'Cónyuge')], max_length=50, null=True, verbose_name='Generación/Relación'),
        ),
        migrations.AlterField(
            model_name='member',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='WhatsApp'),
        ),
    ]
