# Generated by Django 4.2 on 2026-03-29 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_alter_member_options_member_qr_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['last_name_paterno', 'first_name'], 'verbose_name': 'Miembro de la Familia', 'verbose_name_plural': 'Miembros de la Familia'},
        ),
        migrations.RenameField(
            model_name='member',
            old_name='fallecimiento_date',
            new_name='death_date',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='correomail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='member',
            name='address',
        ),
        migrations.RemoveField(
            model_name='member',
            name='estudios',
        ),
        migrations.RemoveField(
            model_name='member',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='member',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='member',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='member',
            name='madrina_de_bautismo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='padrino_de_bautismo',
        ),
        migrations.RemoveField(
            model_name='member',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='member',
            name='whatsapp',
        ),
        migrations.AddField(
            model_name='member',
            name='biografia',
            field=models.TextField(blank=True, null=True, verbose_name='Biografía/Notas Históricas'),
        ),
        migrations.AddField(
            model_name='member',
            name='dni',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='DNI/Pasaporte'),
        ),
        migrations.AddField(
            model_name='member',
            name='lugar_residencia',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar de Residencia'),
        ),
        migrations.AddField(
            model_name='member',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono/WhatsApp'),
        ),
        migrations.AlterField(
            model_name='member',
            name='conyuge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pareja', to='members.member', verbose_name='Cónyuge/Pareja'),
        ),
        migrations.AlterField(
            model_name='member',
            name='foto_principal',
            field=models.ImageField(blank=True, null=True, upload_to='members/photos/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='member',
            name='lugar_nacimiento',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='member',
            name='ocupacion',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Ocupación/Profesión'),
        ),
        migrations.AlterField(
            model_name='member',
            name='qr_code',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to='members/qrcodes/'),
        ),
        migrations.AlterField(
            model_name='member',
            name='relationship',
            field=models.CharField(blank=True, choices=[('TATARABUELO', '1ra Generación (Tatarabuelo/a)'), ('BISABUELO', '2da Generación (Bisabuelo/a)'), ('ABUELO', '3ra Generación (Abuelo/a)'), ('PADRE_MADRE', '4ta Generación (Padre/Madre)'), ('HIJO_HIJA', '5ta Generación (Hijo/a)'), ('NIETO_NIETA', '6ta Generación (Nieto/a)'), ('BISNIETO', '7ma Generación (Bisnieto/a)'), ('TATARANIETO', '8va Generación (Tataranieto/a)'), ('CHOZNO', '9na Generación (Chozno/a)'), ('HERMANO', 'Hermano/a'), ('TIO', 'Tío/a'), ('PRIMO', 'Primo/a'), ('CONYUGE', 'Cónyuge')], max_length=20, null=True, verbose_name='Parentesco Principal'),
        ),
    ]
