# Generated by Django 6.0.3 on 2026-03-31 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='conyuge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pareja', to='members.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='madre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_madre', to='members.member'),
        ),
        migrations.AlterField(
            model_name='member',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hijos_padre', to='members.member'),
        ),
    ]
